"""
Interest Rate Cap pricing example.

Prices a 2Y USD cap on 3M Term SOFR, struck at 5%, under Black-76 (shifted
lognormal) volatility. The first caplet is already fixed as of the valuation
date (2-business-day fixing lag) and is priced at intrinsic value from a
historic fixing; the rest have forward rates implied from consecutive
discount factor ratios and are priced via the selected volatility model.
Cashflow schedule is generated by IRCapFloorModel and discounted by
DCFPricer.
"""

import datetime as dt

from qp.curves.ir_curve import IRCurve
from qp.curves.volatility.flat_vol import FlatVol
from qp.instruments.rates.ir_cap_floor import IRCapFloor
from qp.models.rates.ircapfloor_model import IRCapFloorModel
from qp.price_and_risk.discount_cashflows import DCFPricer, PricingSpec
from qp.time.date.dateroll import Dateroll
from qp.time.date.daycount import Daycount
from qp.utils.maps.currency.currencies import Currency
from qp.utils.maps.general.frequencies import Frequency
from qp.utils.maps.general.payreceive import PayReceive
from qp.utils.maps.rates.cap_floor import CapFloor
from qp.utils.maps.rates.floating_indexes import FloatingIndex

VALUATION_DATE = dt.date(2026, 6, 1)
START_DATE = dt.date(2026, 6, 3)
END_DATE = dt.date(2028, 6, 3)
NOTIONAL = 10_000_000

# TERM_SOFR_3M has a 2-business-day fixing lag, so the first caplet's rate
# (accrual start 2026-06-03, fixing 2026-06-01) is already known as of the
# valuation date. It's priced at intrinsic value from this historic fixing
# rather than via Black-76. The rest are unfixed and priced as options; their
# entries are unused, so NaN placeholders are fine.
HISTORIC_FIXINGS = [0.055, float("nan"), float("nan"), float("nan"),
                     float("nan"), float("nan"), float("nan"), float("nan")]

curve = IRCurve(
    at_date=VALUATION_DATE,
    daycount=Daycount.ACT_360,
    currency=Currency.USD,
    curve_name="USD_SOFR",
    tenors=[0.0, 0.25, 0.5, 1.0, 2.0, 3.0, 5.0],
    discount_factors=[1.0, 0.9875, 0.9750, 0.9505, 0.9048, 0.8607, 0.7788],
)

cap = IRCapFloor(
    currency=Currency.USD,
    notional=NOTIONAL,
    start_date=START_DATE,
    end_date=END_DATE,
    payment_frequency=Frequency.QUARTERLY,
    collateral_currency=Currency.USD,
    daycount=Daycount.ACT_360,
    dateroll=Dateroll.MODIFIED_FOLLOWING,
    pay_receive=PayReceive.RECEIVE,
    index=FloatingIndex.TERM_SOFR_3M,
    strike=0.05,
    cap_floor=CapFloor.CAP,
)

model = IRCapFloorModel(
    valuation_date=VALUATION_DATE,
    floating_curve=curve,
    historic_fixings=HISTORIC_FIXINGS,
    vol_obj=FlatVol(vol=0.20, vol_dc_convention=Daycount.ACT_360),
)

spec = PricingSpec(model=model, instrument=cap, discount_curve=curve)
result = DCFPricer(spec).discount_cashflows()

schedule = model.price(cap)
print("Caplet cashflows (undiscounted):")
for date, cf in zip(schedule.payment_dates, schedule.cashflows):
    print(f"  {date}  USD {cf:,.2f}")

print(f"\nPV (discounted): USD {result[0].value:,.2f}")
