"""
Interest Rate Swap (IRS) pricing example.

Prices a 2Y USD IRS: pay 5% semi-annual fixed, receive SOFR quarterly.
Forward rates are implied from consecutive discount factor ratios.
Cashflow schedules are generated by IRSModel and discounted by DCFPricer.
"""

import datetime as dt

from qp.curves.ir_curve import IRCurve
from qp.instruments.rates.irs import IRS, IRFixedLeg, IRFloatingLeg
from qp.models.rates.irs_model import IRSModel
from qp.price_and_risk.discount_cashflows import DCFPricer, PricingSpec
from qp.time.date.dateroll import Dateroll
from qp.time.date.daycount import Daycount
from qp.utils.maps.currency.currencies import Currency
from qp.utils.maps.general.frequencies import Frequency
from qp.utils.maps.general.payreceive import PayReceive
from qp.utils.maps.rates.floating_indexes import FloatingIndex

VALUATION_DATE = dt.date(2026, 6, 1)
START_DATE = dt.date(2026, 6, 3)
END_DATE = dt.date(2028, 6, 3)
NOTIONAL = 10_000_000

curve = IRCurve(
    at_date=VALUATION_DATE,
    daycount=Daycount.ACT_360,
    currency=Currency.USD,
    curve_name="USD_SOFR",
    tenors=[0.0, 0.25, 0.5, 1.0, 2.0, 3.0, 5.0],
    discount_factors=[1.0, 0.9875, 0.9750, 0.9505, 0.9048, 0.8607, 0.7788],
)

irs = IRS(
    leg_one=IRFixedLeg(
        currency=Currency.USD,
        notional=NOTIONAL,
        start_date=START_DATE,
        end_date=END_DATE,
        payment_frequency=Frequency.SEMI_ANNUAL,
        collateral_currency=Currency.USD,
        daycount=Daycount.THIRTY_360,
        dateroll=Dateroll.MODIFIED_FOLLOWING,
        pay_receive=PayReceive.PAY,
        fixed_rate=0.05,
    ),
    leg_two=IRFloatingLeg(
        currency=Currency.USD,
        notional=NOTIONAL,
        start_date=START_DATE,
        end_date=END_DATE,
        payment_frequency=Frequency.QUARTERLY,
        collateral_currency=Currency.USD,
        daycount=Daycount.ACT_360,
        dateroll=Dateroll.MODIFIED_FOLLOWING,
        pay_receive=PayReceive.RECEIVE,
        index=FloatingIndex.SOFR,
    ),
)

model = IRSModel(valuation_date=VALUATION_DATE, leg_two_curve=curve)

spec = PricingSpec(model=model, instrument=irs, discount_curve=curve)
result = DCFPricer(spec).discount_cashflows()

fixed_schedule, float_schedule = model.price(irs)
print("Fixed leg cashflows (undiscounted):")
for date, cf in zip(fixed_schedule.payment_dates, fixed_schedule.cashflows):
    print(f"  {date}  USD {cf:,.2f}")

print("\nFloat leg cashflows (undiscounted):")
for date, cf in zip(float_schedule.payment_dates, float_schedule.cashflows):
    print(f"  {date}  USD {cf:,.2f}")

print(f"\nPV (discounted): USD {result[0].value:,.2f}")
